# 触发条件：当有新的push或pull request时
on: [push, pull_request]

# 工作流名称：Coverage
name: Coverage

env:
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: default

# 工作流任务：coverage

jobs:
  coverage:
    name: Run cargo coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install grcov
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: grcov
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Run cargo test
        run: bash -c "RUSTUP_TOOLCHAIN=stable RUSTFLAGS="-C instrument-coverage" LLVM_PROFILE_FILE="coverage-%p-%m.profraw" cargo test --all-features"
      - name: Run grcov
        run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "*cargo*" -o lcov.info
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -f lcov.info
